name: web
description: Web platform for watermarks remover project

publish_to: 'none'

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  provider: '>=5.0.0'
  cupertino_icons: '>=1.0.2'
  flutter_dropzone: '>=2.0.1'
  crypto: '3.0.0'
  either_dart: 0.1.1
  http: 0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
