name: web
description: Web platform for watermarks remover project

publish_to: 'none'

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.3.3
  cupertino_icons: ^1.0.2
  flutter_dropzone: ^1.0.10
  crypto: 3.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: '>=1.11.1'

flutter:
  uses-material-design: true
